# Generated by Django 3.2.25 on 2024-10-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPrincipalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasswiseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee', models.IntegerField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('mobile_and_whatsapp', models.BigIntegerField()),
                ('staff_id', models.CharField(max_length=255, unique=True)),
                ('staff_image', models.ImageField(upload_to='staff_img/')),
                ('father_name', models.CharField(max_length=50)),
                ('staff_aadhar', models.BigIntegerField()),
                ('staff_gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('staff_pwd', models.CharField(max_length=255)),
                ('date_of_hire', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('category', models.BooleanField(choices=[(True, 'Teaching Staff'), (False, 'Non-Teaching Staff')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('staff_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_in_years', models.IntegerField()),
                ('image', models.ImageField(upload_to='staff_img/')),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('married_status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Schoolapp.staffenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.CharField(max_length=255, unique=True)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('student_pwd', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_aadhar', models.FileField(null=True, upload_to='documents/')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_mobile', models.CharField(max_length=15)),
                ('guardian_whatsapp', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField()),
                ('parent_aadhar', models.FileField(null=True, upload_to='documents/')),
                ('previous_school_name', models.CharField(max_length=100)),
                ('previous_school_address', models.CharField(max_length=100)),
                ('previous_school_document', models.FileField(null=True, upload_to='documents/')),
                ('health_information', models.CharField(max_length=500)),
                ('health_information_document', models.FileField(null=True, upload_to='documents/')),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('subject_code', models.CharField(max_length=50)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Schoolapp.class')),
                ('staff_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Schoolapp.staffprofile')),
            ],
            options={
                'unique_together': {('subject_name', 'class_assigned')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='student_img/')),
                ('contact_number', models.CharField(max_length=15)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Schoolapp.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('reason', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reports', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('date_recorded', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='Schoolapp.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='Schoolapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField()),
                ('content', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.IntegerField()),
                ('due_date', models.DateField()),
                ('date_of_payment', models.DateField()),
                ('Fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schoolapp.classwisefee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='Schoolapp.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date_range_start', models.DateField()),
                ('attendance_date_range_end', models.DateField()),
                ('total_present_days', models.IntegerField()),
                ('total_absent_days', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Schoolapp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Schoolapp.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='Schoolapp.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('reason', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reports', to='Schoolapp.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField()),
                ('content', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Schoolapp.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_present_days', models.IntegerField()),
                ('total_absent_days', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='Schoolapp.staffenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Schoolapp.staffenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='activities', to='Schoolapp.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exam', models.CharField(max_length=225)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Schoolapp.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Schoolapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='Schoolapp.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions', to='Schoolapp.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='Schoolapp.class')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Schoolapp.staffenrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Schoolapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequestsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='Schoolapp.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='Schoolapp.studentprofile')),
            ],
        ),
    ]
